set(AUTO_GENERATED_WARNING
"########################################################################
This file is AUTOGENERATED, changes you make will not persist.
Do not check into Souce Control.

Edit ../cmake/kernels.cpp.in instead
########################################################################"
)

# read kernel source files and headers
file(READ ${DIR}/src/kernelSrc/prediction.cl PREDICTION_KERNEL)
file(READ ${DIR}/include/kernelInclude/particle.h PARTICLE_HEADER)
file(READ ${DIR}/src/kernelSrc/update.cl UPDATE_KERNEL)

configure_file(${DIR}/cmake/kernels.cpp.in ${DIR}/src/kernels.cpp @ONLY)