set(AUTO_GENERATED_WARNING
"########################################################################
This file is AUTOGENERATED, changes you make will not persist.
Do not check into Souce Control.

Edit ../cmake/kernels.cpp.in instead
########################################################################"
)

# read kernel source files and headers
file(READ src/kernelSrc/prediction.cl PREDICTION_KERNEL)
file(READ include/kernelInclude/particle.h PARTICLE_HEADER)

configure_file(cmake/kernels.cpp.in ${CMAKE_CURRENT_SOURCE_DIR}/src/kernels.cpp @ONLY)
