#ifndef BITONIC_KERNELS_H
#define BITONIC_KERNELS_H

// TODO: change to fit into (gridID, particleID)-Scheme
const char * bitonic_STL_sort_source  =
"__kernel                                           "
"\n void _kbitonic_stl_sort(                    	"
"\n             __global float *input_ptr,        	"
"\n             const unsigned int stage,           "
"\n             const int passOfStage)              "
"\n {                                    			"
"\n                                      			"
"\n      unsigned int  threadId = get_global_id(0);  					"
"\n      unsigned int  pairDistance = 1 << (stage - passOfStage);   	"
"\n      unsigned int  blockWidth = 2 * pairDistance;    				"
"\n      unsigned int  temp;  											"
"\n                                                          			"
"\n      bool compareResult;                                      		"
"\n      unsigned int  leftId = (threadId & (pairDistance - 1)) + 		" 
"			(threadId >> (stage - passOfStage) ) * blockWidth;  		" 
"\n      unsigned int  rightId = leftId + pairDistance;  				" 
"\n        																" 
"\n      float leftElementXYZ[3];  							" 
"\n 	 float rightElementXYZ[3];							"
"\n    	 float *greater, *lesser;  						" 
"\n 													"
"\n		leftElementXYZ[0] = input_ptr[leftId*3 + 0];	"
"\n		leftElementXYZ[1] = input_ptr[leftId*3 + 1];	"
"\n		leftElementXYZ[2] = input_ptr[leftId*3 + 2];	"
"\n		rightElementXYZ[0] = input_ptr[rightId*3 + 0];	"
"\n		rightElementXYZ[1] = input_ptr[rightId*3 + 1];	"
"\n		rightElementXYZ[2] = input_ptr[rightId*3 + 2];	"
"\n 												"
"\n      unsigned int sameDirectionBlockWidth = threadId >> stage;   	" 
"\n      unsigned int sameDirection = sameDirectionBlockWidth & 0x1; 	" 
"\n      																" 
"\n      temp = sameDirection ? rightId : temp; 						" 
"\n      rightId = sameDirection ? leftId : rightId; 					" 
"\n      leftId = sameDirection ? temp : leftId;						" 
"\n       																" 
"\n      compareResult = (leftElementXYZ[0] < rightElementXYZ[0]); 			" 
"\n       																" 
"\n      greater = compareResult ? rightElement : leftElement; 		" 
"\n      lesser = compareResult ? leftElement : rightElement; 		" 
"\n       																" 
"\n 	input_ptr[leftId*9 + 0] = lesser[0];   "
"\n 	input_ptr[leftId*9 + 1] = lesser[1];   "
"\n 	input_ptr[leftId*9 + 2] = lesser[2];   "
"\n 	input_ptr[leftId*9 + 3] = lesser[3];   "
"\n 	input_ptr[leftId*9 + 4] = lesser[4];   "
"\n 	input_ptr[leftId*9 + 5] = lesser[5];   "
"\n 	input_ptr[leftId*9 + 6] = lesser[6];   "
"\n 	input_ptr[leftId*9 + 7] = lesser[7];   "
"\n 	input_ptr[leftId*9 + 8] = lesser[8];   "
"\n 	input_ptr[rightId*9 + 0] = greater[0];   "
"\n 	input_ptr[rightId*9 + 1] = greater[1];   "
"\n 	input_ptr[rightId*9 + 2] = greater[2];   "
"\n 	input_ptr[rightId*9 + 3] = greater[3];   "
"\n 	input_ptr[rightId*9 + 4] = greater[4];   "
"\n 	input_ptr[rightId*9 + 5] = greater[5];   "
"\n 	input_ptr[rightId*9 + 6] = greater[6];   "
"\n 	input_ptr[rightId*9 + 7] = greater[7];   "
"\n 	input_ptr[rightId*9 + 8] = greater[8];   "
"\n }     										" 
; 


#endif

